<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="FormInputBatch.aspx.cs" Inherits="BioPM.FormInputBatch" %>

<!DOCTYPE html>
<script runat="server">
    protected void Page_Load(object sender, EventArgs e)
    {
        if (Session["username"] == null && Session["password"] == null) Response.Redirect("PageLogin.aspx");
        //if (!IsPostBack) SetDataToForm();
    }
    protected void sessionCreator()
    {
        Session["username"] = "K495";
        Session["name"] = "ALLAN PRAKOSA";
        Session["password"] = "admin1234";
        Session["role"] = "111111";
    }

    
    /*
    protected void SetExistingBagian()
    {
        ddlBagian.Items.Clear();
        ddlActivity.Items.Clear();
        foreach (object[] data in BioPM.ClassObjects.RiskCatalog.GetRisk())
        {
            ddlBagian.Items.Add(new List(data[0].ToString()));
            ddlActivity.Items.Add(new List(data[0].ToString());
        }
    }
    */
   
    /*
    protected void SetProduct()
    {
        ddlProductType.Items.Clear();
        foreach (object[] data in BioPM.ClassObjects.BatchCatalog.GetProductByCostCenter(Session["coctr"].ToString()))
        {
            ddlProductType.Items.Add(new ListItem(data[1].ToString(), data[0].ToString()));
        }
    }

    protected void SetDataToForm()
    {
        SetProduct();
    }
    */
    
    protected void InsertRiskIntoDatabase()
    {
        //string REGID = (BioPM.ClassObjects.RiskCatalog.GetRiskMatchID() + 1).ToString();
        //string[] REGID = new string[2];
        //REGID[0] = ddlBagian.SelectedItem.Text;
        //REGID[1] = ddlActivity.SelectedItem.Text;
        
        string REGIDstr = ddlBagian.SelectedItem.Text + "-" + ddlActivity.SelectedItem.Text + "-" + txtREGID.Text;
        
        BioPM.ClassObjects.RiskCatalog.InsertRisk(DateTime.Now.ToString(), REGIDstr, txtRKEVT.Text, ddlRKACT.SelectedItem.Text, ddlRKFNC.SelectedItem.Text, txtSuppDt.Text, txtRiskCause.Text, txtRiskLoc.Text, ddlRKMGT.SelectedItem.Text,txtFrequency.Text, Session["username"].ToString());
    }
    
    /*
    protected void InsertBatchIntoDatabasse()
    {          
        string BATID = (BioPM.ClassObjects.BatchCatalog.GetBatchMaxID() + 1).ToString();
        BioPM.ClassObjects.BatchCatalog.InsertBatch(BATID, txtProductionDate.Text, txtBatch.Text, ddlProductType.SelectedValue, txtDetail.Text, Session["username"].ToString());
    }
    */
    protected void btnAdd_Click(object sender, EventArgs e)
    {
        if (IsPostBack) InsertRiskIntoDatabase();
        Response.Redirect("PageRisk.aspx");
    }

    protected void btnCancel_Click(object sender, EventArgs e)
    {
        Response.Redirect("PageUserPanel.aspx");
    }
    
</script>

<html lang="en">
<head>
    <% Response.Write(BioPM.ClassScripts.BasicScripts.GetMetaScript()); %>

    <title>BATCH ENTRY</title>

    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetCoreStyle()); %>
    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetFormStyle()); %>
    <% Response.Write(BioPM.ClassScripts.StyleScripts.GetCustomStyle()); %>
</head>

<body>

<section id="container" >
 
<!--header start--> 
 <%Response.Write( BioPM.ClassScripts.SideBarMenu.TopMenuElement(Session["name"].ToString()) ); %> 
<!--header end-->
   
<!--left side bar start-->
 <%Response.Write(BioPM.ClassScripts.SideBarMenu.LeftSidebarMenuElementAutoGenerated(Session["username"].ToString())); %> 
<!--left side bar end-->

    <!--main content start-->
    <section id="main-content">
        <section class="wrapper">
        <!-- page start-->

        <div class="row">
            <div class="col-sm-12">
                <section class="panel">
                    <header class="panel-heading">
                        RISK ENTRY FORM
                          <span class="tools pull-right">
                            <a class="fa fa-chevron-down" href="javascript:;"></a>
                            <a class="fa fa-times" href="javascript:;"></a>
                         </span>
                    </header>
                    <div class="panel-body">
                        <form id="Form1" class="form-horizontal " runat="server" >
                         
                        <div class="form-group">
                            <label class="col-sm-3 control-label"> NO REGISTRASI </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:DropDownList ID="ddlBagian" runat="server" class="form-control m-bot15" DataSourceID="sqlRISK_BAGIAN" DataTextField="KDBAG" DataValueField="KDBAG"></asp:DropDownList>
                                <asp:SqlDataSource ID="sqlRISK_BAGIAN" runat="server" ConnectionString="<%$ ConnectionStrings:DefaultConnection %>" SelectCommand="SELECT [biolegal].[BAGIAN].[KDBAG]
FROM [biolegal].[BAGIAN]
"></asp:SqlDataSource>
                                <asp:DropDownList ID="ddlActivity" runat="server" class="form-control m-bot15" DataSourceID="sqlRISK_ACTIVITY" DataTextField="KDACT" DataValueField="KDACT"></asp:DropDownList>
                                <asp:SqlDataSource ID="sqlRISK_ACTIVITY" runat="server" ConnectionString="<%$ ConnectionStrings:DefaultConnection %>" SelectCommand="SELECT [biolegal].[RISK_ACTIVITY].[KDACT]
FROM [biolegal].[RISK_ACTIVITY]"></asp:SqlDataSource>
                                <asp:TextBox ID="txtREGID" runat="server" class="form-control m-bot15"></asp:TextBox>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> RISK EVENT </label>
                            <div class="col-lg-3 col-md-4">
                                <asp:TextBox ID="txtRKEVT" runat="server" class="form-control m-bot15" placeholder="RISK EVENT" ></asp:TextBox>
                            </div>
                        </div>
                            
                        <div class="form-group">
                            <label class="col-sm-3 control-label"> RISK ACTIVITY </label>
                            <div class="col-md-4 col-lg-3">
                                <asp:DropDownList ID="ddlRKACT" runat="server" class="form-control m-bot15" DataSourceID="sqlRISK_ACTIVITY_NAME" DataTextField="NMACT" DataValueField="NMACT"></asp:DropDownList>
                                <asp:SqlDataSource ID="sqlRISK_ACTIVITY_NAME" runat="server" ConnectionString="<%$ ConnectionStrings:DefaultConnection %>" SelectCommand="SELECT [biolegal].[RISK_ACTIVITY].[NMACT]
FROM [biolegal].[RISK_ACTIVITY]"></asp:SqlDataSource>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> RISK FUNCTION </label>
                            <div class="col-md-4 col-lg-3">
                                <asp:DropDownList ID="ddlRKFNC" runat="server" class="form-control m-bot15" DataSourceID="sqlRISK_FUNC" DataTextField="NMFNC" DataValueField="NMFNC"></asp:DropDownList>
                                <asp:SqlDataSource ID="sqlRISK_FUNC" runat="server" ConnectionString="<%$ ConnectionStrings:DefaultConnection %>" SelectCommand="SELECT [biolegal].[RISK_FUNCTION].[NMFNC]
FROM [biolegal].[RISK_FUNCTION]"></asp:SqlDataSource>
                            </div>
                        </div>

                       <div class="form-group">
                            <label class="col-sm-3 control-label"> SUPPORTED DATA </label>
                            <div class="col-md-4 col-lg-3">
                                    <asp:TextBox ID="txtSuppDt" runat="server" class="form-control m-bot15" placeholder="SUPPORTED DATA" ></asp:TextBox>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> RISK CAUSE </label>
                            <div class="col-md-4 col-lg-3">
                                <asp:TextBox ID="txtRiskCause" runat="server" class="form-control m-bot15" placeholder="RISK CAUSE" ></asp:TextBox>
                            </div>
                        </div>

                       <div class="form-group">
                            <label class="col-sm-3 control-label"> RISK LOCATION </label>
                            <div class="col-md-4 col-lg-3">
                                <asp:TextBox ID="txtRiskLoc" runat="server" class="form-control m-bot15" placeholder="RISK LOCATION" ></asp:TextBox>
                            </div>
                        </div>


                         <div class="form-group">
                            <label class="col-sm-3 control-label"> RISK PROBABILITY </label>
                            <div class="col-md-4 col-lg-3">
                                <asp:Button class="btn btn-round btn-primary" ID="Button1" runat="server" Text="Add"/>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> RISK IMPACT </label>
                            <div class="col-md-4 col-lg-3">
                                 <asp:TextBox ID="txtRiskImpact" runat="server" class="form-control m-bot15" placeholder="RISK IMPACT" ></asp:TextBox>
                            </div>
                        </div>                        

                       <div class="form-group">
                            <label class="col-sm-3 control-label"> RISK STATUS </label>
                            <div class="col-md-4 col-lg-3">
                                    <asp:TextBox ID="txtRiskStatus" runat="server" class="form-control m-bot15" placeholder="RISK STATUS" ></asp:TextBox>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> RISK MAINTENANCE </label>
                            <div class="col-md-4 col-lg-3">
                                <asp:DropDownList ID="ddlRKMGT" runat="server" class="form-control m-bot15" DataSourceID="sqlRISK_MANAGEMENT" DataTextField="NMMGT" DataValueField="NMMGT" ></asp:DropDownList>
                                <asp:SqlDataSource ID="sqlRISK_MANAGEMENT" runat="server" ConnectionString="<%$ ConnectionStrings:DefaultConnection %>" SelectCommand="SELECT [biolegal].[RISK_MANAGEMENT].[NMMGT]
FROM [biolegal].[RISK_MANAGEMENT]"></asp:SqlDataSource>
                            </div>
                        </div>                        

                       <div class="form-group">
                            <label class="col-sm-3 control-label"> FREQUENCY </label>
                            <div class="col-md-4 col-lg-3">
                                    <asp:TextBox ID="txtFrequency" runat="server" class="form-control m-bot15" placeholder="RISK FREQUENCY" ></asp:TextBox>
                            </div>
                        </div>

                        <div class="form-group">
                            <label class="col-sm-3 control-label"> </label>
                            <div class="col-lg-3 col-md-3">
                                <asp:Button class="btn btn-round btn-primary" ID="btnAdd" runat="server" Text="Add" OnClick="btnAdd_Click"/>
                                <asp:Button class="btn btn-round btn-primary" ID="btnCancel" runat="server" Text="Cancel" OnClick="btnCancel_Click"/>
                            </div>
                        </div>
                            
                        </form>
                    </div>
                    
                </section>
            </div>
        </div>
        <!-- page end-->
        </section>
    </section>
    <!--main content end-->
<!--right sidebar start-->
    <%Response.Write(BioPM.ClassScripts.SideBarMenu.RightSidebarMenuElement()); %> 
<!--right sidebar end-->
</section>

<!-- Placed js at the end of the document so the pages load faster -->
   
<% Response.Write(BioPM.ClassScripts.JS.GetCoreScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetCustomFormScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetInitialisationScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetPieChartScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetSparklineChartScript()); %>
<% Response.Write(BioPM.ClassScripts.JS.GetFlotChartScript()); %>
</body>
</html>
